### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by Decavoid** [handzlikchris/Unity.MissingUnityEvents#4] opened 2021-01-21 12:01 UTC
Unity 2020.1.14f1
Weaving fails with an error:

DirectoryNotFoundException: Could not find a part of the path 'D:\Program Files\Unity(Hub)\2020.1.14f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\sources\cxx-stl\llvm-libc++\test\std\thread\thread.mutex\thread.mutex.requirements\thread.sharedtimedmutex.requirements\thread.sharedtimedmutex.class'.
Assets.MissingUnityEvents.Editor.ConfigPersistableEditorWindow`1[T].OnGUI () (at Library/PackageCache/missingunityevents@9da57fbc4b/Editor/ConfigPersistableEditorWindow.cs:45)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <bd45cfd5e8c2437da9b5cc29b19f336f>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <bd45cfd5e8c2437da9b5cc29b19f336f>:0)
UnityEditor.DockArea.OldOnGUI () (at <bd45cfd5e8c2437da9b5cc29b19f336f>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <93ba6ea0bbfd4de09b538244d248af02>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <6cf4b8f7a4344e9e9df60cc4c1690d8c>:0)
![Clipboard01](https://user-images.githubusercontent.com/1127000/105348521-e57f9b00-5c01-11eb-9953-76b2977559e0.jpg)

**Comment by handzlikchris** [comment] 2021-01-21 13:25
Hi @Andreyul 

The error would suggest that the issue is before hitting 'Weave Events to DLL' at the stage of generating GUI for that editor. Is that the case?

If so perhaps Unity can not access Pligin Executable Path for whatever reason (can see that's empty) - you might want to either debug why that's the case or perhaps picking manually would help.

If it happened at after clicking the 'Weave Events to DLL' button then we'd need to look at the error that comes from command line tool (that repo is just a wrapper around it and real issue will be in console app).

You can place a breakpoint or Debug.Log in `Assets.MissingUnityEvents.Editor.EventILWeaverCommandLineArgsGenerator.GenerateAddEventsCommandLineArgs` and then try to re-weave - this will give you command line tool that's executed, with that probably easiest to just run it from command line and see what's happening.

Maybe it picked up some wrong input files as `-t` parameter.

If that still doesn't bring you closer to a solution you can pull source code for actual command line tool that does the work 
`https://github.com/handzlikchris/AddingEventsToCompiled3rdPartyLibrary` then run debug on that with your parameters - that should give you better idea what's happening.

Hope that helps,
Chris

**Comment by Decavoid** [comment] 2021-01-21 14:03
The exception is thrown by DirectoryInfo.GetFiles method in EventILWeaverCommandLineArgsGenerator.GetUnityRequiredDllPaths(). This is related to file paths that are too long.

**Comment by handzlikchris** [comment] 2021-01-21 15:54
Great - thanks for letting me know, I'll close the issue.

**Closed as completed by handzlikchris** 2021-01-21 15:54 UTC

**Comment by ProtoxiDe22** [comment] 2021-03-15 11:28
@Andreyul I'm facing the exact same issue, and Ican't really move the path it's looking for to a shorter path since it's just unity files, and i can't find a solution. i tried enabling long path support on windows but that didn't help, how did you get around this problem?

the path my editor is trying to access is `C:\Program Files\Unity\Hub\Editor\2020.2.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\sources\cxx-stl\llvm-libc++\test\std\experimental\utilities\propagate_const\propagate_const.nonmembers\propagate_const.comparison_function_objects` and that directory does exist
